require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StudentActivitiesController do

  # This should return the minimal set of attributes required to create a valid
  # StudentActivity. As you add validations to StudentActivity, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "user_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StudentActivitiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all student_activities as @student_activities" do
      student_activity = StudentActivity.create! valid_attributes
      get :index, {}, valid_session
      assigns(:student_activities).should eq([student_activity])
    end
  end

  describe "GET show" do
    it "assigns the requested student_activity as @student_activity" do
      student_activity = StudentActivity.create! valid_attributes
      get :show, {:id => student_activity.to_param}, valid_session
      assigns(:student_activity).should eq(student_activity)
    end
  end

  describe "GET new" do
    it "assigns a new student_activity as @student_activity" do
      get :new, {}, valid_session
      assigns(:student_activity).should be_a_new(StudentActivity)
    end
  end

  describe "GET edit" do
    it "assigns the requested student_activity as @student_activity" do
      student_activity = StudentActivity.create! valid_attributes
      get :edit, {:id => student_activity.to_param}, valid_session
      assigns(:student_activity).should eq(student_activity)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StudentActivity" do
        expect {
          post :create, {:student_activity => valid_attributes}, valid_session
        }.to change(StudentActivity, :count).by(1)
      end

      it "assigns a newly created student_activity as @student_activity" do
        post :create, {:student_activity => valid_attributes}, valid_session
        assigns(:student_activity).should be_a(StudentActivity)
        assigns(:student_activity).should be_persisted
      end

      it "redirects to the created student_activity" do
        post :create, {:student_activity => valid_attributes}, valid_session
        response.should redirect_to(StudentActivity.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved student_activity as @student_activity" do
        # Trigger the behavior that occurs when invalid params are submitted
        StudentActivity.any_instance.stub(:save).and_return(false)
        post :create, {:student_activity => { "user_id" => "invalid value" }}, valid_session
        assigns(:student_activity).should be_a_new(StudentActivity)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StudentActivity.any_instance.stub(:save).and_return(false)
        post :create, {:student_activity => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested student_activity" do
        student_activity = StudentActivity.create! valid_attributes
        # Assuming there are no other student_activities in the database, this
        # specifies that the StudentActivity created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StudentActivity.any_instance.should_receive(:update_attributes).with({ "user_id" => "1" })
        put :update, {:id => student_activity.to_param, :student_activity => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested student_activity as @student_activity" do
        student_activity = StudentActivity.create! valid_attributes
        put :update, {:id => student_activity.to_param, :student_activity => valid_attributes}, valid_session
        assigns(:student_activity).should eq(student_activity)
      end

      it "redirects to the student_activity" do
        student_activity = StudentActivity.create! valid_attributes
        put :update, {:id => student_activity.to_param, :student_activity => valid_attributes}, valid_session
        response.should redirect_to(student_activity)
      end
    end

    describe "with invalid params" do
      it "assigns the student_activity as @student_activity" do
        student_activity = StudentActivity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StudentActivity.any_instance.stub(:save).and_return(false)
        put :update, {:id => student_activity.to_param, :student_activity => { "user_id" => "invalid value" }}, valid_session
        assigns(:student_activity).should eq(student_activity)
      end

      it "re-renders the 'edit' template" do
        student_activity = StudentActivity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StudentActivity.any_instance.stub(:save).and_return(false)
        put :update, {:id => student_activity.to_param, :student_activity => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested student_activity" do
      student_activity = StudentActivity.create! valid_attributes
      expect {
        delete :destroy, {:id => student_activity.to_param}, valid_session
      }.to change(StudentActivity, :count).by(-1)
    end

    it "redirects to the student_activities list" do
      student_activity = StudentActivity.create! valid_attributes
      delete :destroy, {:id => student_activity.to_param}, valid_session
      response.should redirect_to(student_activities_url)
    end
  end

end
